# Generated by Django 2.1.4 on 2019-02-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='api_url',
        ),
    ]
