# Generated by Django 2.1.4 on 2019-02-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_remove_deployment_api_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='website_url',
            new_name='url',
        ),
    ]
