# Generated by Django 2.1.4 on 2019-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_deployment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('TESTING', 'Testing'), ('DEVELOP', 'Development')], default='PRODUCTION', max_length=30),
        ),
    ]
