# Generated by Django 2.1.4 on 2019-02-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country'),
        ('software', '0005_deployment_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country'),
        ),
    ]
