# Generated by Django 2.1.4 on 2019-02-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country'),
        ('software', '0008_appserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['sql_server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SqlServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('domain_name', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='database',
            name='sql_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.SqlServer'),
        ),
    ]
