# Generated by Django 2.1.4 on 2019-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_sqlserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the deployment is active.', verbose_name='Is active'),
        ),
    ]
