version: "3.7"

networks:
  backend:
    external: true

services:
  web:
    build: .
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - backend
    ports:
      - "${PORT}:8000"
    restart: always
