# Generated by Django 2.1.4 on 2019-01-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
